### ISSUE TITLE
The name of the root UML model element should correspond to the project name

### ISSUE THREAD

**Issue by itsdani** [IncQueryLabs/incquery-evm-jdt#35]
Currently the root element of the UML model corresponds to the name of a single top-level package, however in a Java project there can be multiple top-level packages. To resolve this issue the name of the root element should match the name of the Java project, and every package should be represented as a package in the UML model.

**Comment by itsdani** [comment]
The Java to UML direction is fixed in #42

**Comment by abelhegedus** [comment]
Root model name is not relevant any more.
